export {Inicial as PageInicial} from "./Inicial"
export {Produto as PageProduto} from "./Produto"
export {Layout as PageLayout} from "./Layout"
export {Cadastrar as PageCdastrar} from "./Cadastrar"
export {Login as PageLogin} from "./Login"
export {Adm as PageAdmin} from "./Admin"